### PR TITLE
feat(avalancheup): automatic subnet installation in apply

### PR DESCRIPTION
**Pull request by gyuho**
Address https://github.com/ava-labs/avalanche-ops/issues/390.

Replace https://github.com/ava-labs/avalanche-ops/pull/427.

### CODE REVIEW

**Review by exdx — APPROVED** [review]
I noticed no new flags were added. The idea is to ensure that a subnet gets installed via `apply` always?

**Comment by gyuho** [comment]
The new flags were already added but weren't implemented

**Comment by exdx** [comment]
Running `apply` on this branch I got the following:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/dan.sover/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-manager-0.29.5/src/s3/mod.rs:463:59
```

Diagnosing further

**Comment by exdx** [comment]
https://github.com/gyuho/aws-manager/blob/d278d894c1546d2c82cddfac907c565d28410d1e/src/s3/mod.rs#L463

**Comment by gyuho** [comment]
@exdx Can you retry? Seen those error with flaky wifi... Retry should work.

**Pull request merged**
